updated

diff --git a/jenkinsfile_skipstage b/jenkinsfile_skipstage
--- a/jenkinsfile_skipstage
+++ b/jenkinsfile_skipstage
@@ -9,8 +9,10 @@ pipeline{
                 script{
                     try{
                         echo "my name is Manjunath"
+                        sh 'exit 1'
                     }
                     catch (err) {
+                        echo "caught error: ${err}"
                          skipStage = false
                     }
                 }
